/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

import org.gradle.api.plugins.jvm.JvmTestSuite
import org.gradle.kotlin.dsl.*

plugins {
    id("buildlogic.java-common-conventions")
}

testing {
    suites {
        // Ensure the built-in test suite uses JUnit Jupiter (configured in java-common-conventions)
        val test by getting(JvmTestSuite::class)

        register<JvmTestSuite>("integrationTest") {
            useJUnitJupiter("5.12.1")

            dependencies {
                implementation(project())
            }

            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(test)
                    }
                }
            }
        }
    }
}

configurations.named("integrationTestImplementation") {
    extendsFrom(configurations.named("implementation").get())
    extendsFrom(configurations.named("testImplementation").get())
}

configurations.named("integrationTestRuntimeOnly") {
    extendsFrom(configurations.named("runtimeOnly").get())
    extendsFrom(configurations.named("testRuntimeOnly").get())
}

tasks.named("check") {
    dependsOn(testing.suites.named("integrationTest"))
}
